GET http://localhost:3001/account
Accept: application/json

###

POST http://localhost:3001/users/sign_in
Content-Type: application/json

{
    "user": {
        "email": "testdsadasd3@example.com",
        "password": "12345678"
    }
}

###

DELETE http://localhost:3001/users/sign_out
Content-Type: application/json


###

POST http://localhost:3001/boxers
Content-Type: application/json

{
    "boxer": {
        "first_name": "zacky",
        "last_name": "wacky",
        "height": 176,
        "weight":74,
        "reach": 71,
        "stance": "Orthodox",
        "gym_id": 4,
        "avatar": "fight-club-api/app/assets/images/default-avatar.jpeg"
    }
}